language: java
services:
  - docker
os:
  - linux
jdk:
  - openjdk8
script:
  - mvn --fail-at-end --quiet test

cache:
  directories:
  - "$HOME/.m2"
install:
  - echo 'Override Travis-ci install step'
